"""Associate PV installations with synthetic feeder/transformer context.

Everything in this module operates on SYNTHETIC network data generated by
``src.synthetic_data`` for demonstration purposes. The "hosting capacity
status" indicators are simple illustrative heuristics (a rough ratio of
observed + estimated PV capacity to transformer rated capacity) and are
explicitly NOT a substitute for a formal distribution-impact study or
power-flow analysis. See the methodology page for the exact thresholds used.
"""

from __future__ import annotations

from typing import Optional

import geopandas as gpd
import pandas as pd

from src.geometry_utils import estimate_utm_crs
from src.models import REVIEW_END_STATE_VALUES, ChangeType, HostingCapacityStatus

# Illustrative-only thresholds for the demo hosting-capacity indicator.
REVIEW_RECOMMENDED_RATIO = 0.40
MONITOR_RATIO = 0.20
REVIEW_RECOMMENDED_ALERT_COUNT = 5


def assign_transformer_context(
    installations: gpd.GeoDataFrame, transformers: gpd.GeoDataFrame
) -> gpd.GeoDataFrame:
    """Assign each installation its nearest synthetic transformer/feeder."""
    if installations.empty or transformers.empty:
        result = installations.copy()
        result["transformer_id"] = None
        result["feeder_id"] = None
        result["distance_to_transformer_m"] = None
        return result

    combined = gpd.GeoDataFrame(
        pd.concat([installations[["geometry"]], transformers[["geometry"]]], ignore_index=True), crs="EPSG:4326"
    )
    utm = estimate_utm_crs(combined)

    # Reproject full geometries to meters *before* taking centroids (more accurate
    # than centroiding in degrees), then use the projected centroid for nearest-join.
    installs_utm = installations.to_crs(utm)
    installs_proj = installations.copy()
    installs_proj = installs_proj.set_geometry(installs_utm.geometry.centroid, crs=utm)
    tx_proj = transformers.to_crs(utm)

    joined = gpd.sjoin_nearest(
        installs_proj, tx_proj[["transformer_id", "feeder_id", "geometry"]], how="left", distance_col="distance_to_transformer_m"
    )
    joined = joined.drop(columns=[c for c in ["index_right"] if c in joined.columns])
    joined = joined[~joined.index.duplicated(keep="first")]

    result = installations.copy()
    result["transformer_id"] = joined["transformer_id"].values
    result["feeder_id"] = joined["feeder_id"].values
    result["distance_to_transformer_m"] = joined["distance_to_transformer_m"].round(1).values
    return result


def compute_transformer_summary(
    installations_2025_with_context: pd.DataFrame,
    transformers: pd.DataFrame,
    alerts: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Aggregate installation/alert data by synthetic transformer.

    Expects ``installations_2025_with_context`` to include columns
    ``transformer_id``, ``change_type``, and ``estimated_capacity_kw``.
    """
    tx = transformers.drop(columns="geometry", errors="ignore").copy()
    if installations_2025_with_context.empty:
        tx["installation_count"] = 0
        tx["new_installation_count"] = 0
        tx["estimated_new_pv_capacity_kw"] = 0.0
        tx["existing_estimated_capacity_kw"] = 0.0
        tx["unresolved_alert_count"] = 0
        tx["pv_load_ratio"] = None
        tx["hosting_capacity_status"] = HostingCapacityStatus.DATA_INCOMPLETE.value
        return tx

    df = installations_2025_with_context.copy()
    not_removed = df[df["change_type"] != ChangeType.POTENTIALLY_REMOVED.value]

    grp = not_removed.groupby("transformer_id")
    installation_count = grp.size().rename("installation_count")

    is_new = not_removed["change_type"].isin([ChangeType.NEWLY_OBSERVED.value])
    is_new_or_expanded = not_removed["change_type"].isin([ChangeType.NEWLY_OBSERVED.value, ChangeType.EXPANDED.value])

    new_installation_count = (
        not_removed[is_new].groupby("transformer_id").size().rename("new_installation_count")
    )
    estimated_new_capacity = (
        not_removed[is_new_or_expanded].groupby("transformer_id")["estimated_capacity_kw"].sum().rename("estimated_new_pv_capacity_kw")
    )
    existing_capacity = (
        not_removed[~is_new_or_expanded].groupby("transformer_id")["estimated_capacity_kw"].sum().rename("existing_estimated_capacity_kw")
    )

    tx = tx.set_index("transformer_id")
    tx = tx.join(installation_count).join(new_installation_count).join(estimated_new_capacity).join(existing_capacity)
    tx[["installation_count", "new_installation_count"]] = tx[["installation_count", "new_installation_count"]].fillna(0).astype(int)
    tx[["estimated_new_pv_capacity_kw", "existing_estimated_capacity_kw"]] = tx[
        ["estimated_new_pv_capacity_kw", "existing_estimated_capacity_kw"]
    ].fillna(0.0).round(2)

    if alerts is not None and not alerts.empty and "transformer_id" in alerts.columns:
        # "Unresolved" = the case has not reached either end state (Registered
        # or False positive) yet — covers For inspection / For registration /
        # Ongoing registration, not just the initial state.
        if "review_status" in alerts.columns:
            unresolved = alerts[~alerts["review_status"].isin(REVIEW_END_STATE_VALUES)]
        else:
            unresolved = alerts
        unresolved_count = unresolved.groupby("transformer_id").size().rename("unresolved_alert_count")
        tx = tx.join(unresolved_count)
    else:
        tx["unresolved_alert_count"] = 0
    tx["unresolved_alert_count"] = tx["unresolved_alert_count"].fillna(0).astype(int)

    tx = tx.reset_index()
    # Exposed as its own column (not just folded into the status label) so
    # the map/table can show *why* a transformer is flagged — "PV load is
    # 47% of rated capacity" is legible on its own; a red dot by itself
    # isn't.
    tx["pv_load_ratio"] = tx.apply(_pv_load_ratio, axis=1)
    tx["hosting_capacity_status"] = tx.apply(_hosting_status_row, axis=1)
    return tx


def _pv_load_ratio(row: pd.Series) -> Optional[float]:
    """Recorded + newly observed/expanded PV capacity as a fraction of the
    transformer's rated capacity. ``None`` when rated capacity is missing or
    zero (shows up downstream as "Data incomplete")."""
    rated_kva = row.get("rated_capacity_kva")
    if not rated_kva or rated_kva <= 0:
        return None
    total_pv_kw = (row.get("recorded_pv_capacity_kw") or 0.0) + (row.get("estimated_new_pv_capacity_kw") or 0.0)
    return total_pv_kw / rated_kva


def _hosting_status_row(row: pd.Series) -> str:
    ratio = row.get("pv_load_ratio")
    if ratio is None or pd.isna(ratio):
        return HostingCapacityStatus.DATA_INCOMPLETE.value

    unresolved = row.get("unresolved_alert_count", 0) or 0
    if ratio >= REVIEW_RECOMMENDED_RATIO or unresolved >= REVIEW_RECOMMENDED_ALERT_COUNT:
        return HostingCapacityStatus.REVIEW_RECOMMENDED.value
    if ratio >= MONITOR_RATIO or row.get("new_installation_count", 0) >= 3:
        return HostingCapacityStatus.MONITOR.value
    return HostingCapacityStatus.LOW_CONCERN.value
